name: AntiGrief
main: com.crowebird.bukkit.plugins.AntiGrief.AntiGrief
version: 1.0.2

commands:
  ag:
    description: AntiGrief Commands
    usage:
      - 'Please see the wiki for all commands!'
      